## Preprocessing

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN", "NAME"], 1)
application_df.head()

<ipython-input-7-2d68d3c6bb00>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN", "NAME"], 1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
application_counts[application_counts < 500].index

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object')

In [11]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [14]:
class_counts[class_counts > 10]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [15]:
 # Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [16]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [35]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis="columns").values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [36]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [40]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_feature = len(X_train[0])
hidden_nodes_layers1 = 80
hidden_nodes_layers2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers1, input_dim=number_input_feature, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers2, activation="relu")
)

# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1, activation="relu")
)

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 80)                3520

 dense_2 (Dense)             (None, 30)                2430

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [42]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [43]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.8941 - accuracy: 0.6990
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7935 - accuracy: 0.7009
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.8352 - accuracy: 0.7167
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 1.3103 - accuracy: 0.6873
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.8000 - accuracy: 0.7154
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7904 - accuracy: 0.7116
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.9337 - accuracy: 0.7075
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.8442 - accuracy: 0.7092
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.8000 - accuracy: 0.7237
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.8310 - accuracy: 0.7210
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7971 - accuracy: 0.7207
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7836 - accuracy: 0.7254
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7895 - accuracy: 0.7247
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7979 - accuracy: 0.7137
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7871 - accuracy: 0.7091
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6677 - accuracy: 0.7220
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6576 - accuracy: 0.7303
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6448 - accuracy: 0.7246
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6465 - accuracy: 0.7308
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6691 - accuracy: 0.7294
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6495 - accuracy: 0.7307
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6483 - accuracy: 0.7313
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6542 - accuracy: 0.7283
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6573 - accuracy: 0.7212
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6455 - accuracy: 0.7250
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6260 - accuracy: 0.7315
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6071 - accuracy: 0.7313
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6016 - accuracy: 0.7298
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5987 - accuracy: 0.7329
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6267 - accuracy: 0.7315
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6293 - accuracy: 0.7327
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6174 - accuracy: 0.7325
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6197 - accuracy: 0.7317
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5910 - accuracy: 0.7334
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5887 - accuracy: 0.7281
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5830 - accuracy: 0.7315
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5818 - accuracy: 0.7300
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5824 - accuracy: 0.7313
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5719 - accuracy: 0.7312
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7319
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7336
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7343
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7346
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5705 - accuracy: 0.7320
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7334
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5680 - accuracy: 0.7337
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5698 - accuracy: 0.7283
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7340
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5741 - accuracy: 0.7302
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5702 - accuracy: 0.7314
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7347
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7342
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7341
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5700 - accuracy: 0.7339
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5695 - accuracy: 0.7316
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5842 - accuracy: 0.7349
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7346
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7343
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7332
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7336
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7350
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7340
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5722 - accuracy: 0.7290
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5562 - accuracy: 0.7350
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5562 - accuracy: 0.7352
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7369
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7355
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7357
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7364
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7360
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7379
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7364
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5719 - accuracy: 0.7341
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7341
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7365
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5708 - accuracy: 0.7363
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5662 - accuracy: 0.7380
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7355
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7345
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7352
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7376
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5637 - accuracy: 0.7339
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5623 - accuracy: 0.7325
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7371
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7360
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7355
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7367
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7367
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7387
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7375
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7379
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5617 - accuracy: 0.7353
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5717 - accuracy: 0.7386
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6034 - accuracy: 0.7375
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6072 - accuracy: 0.7373
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6085 - accuracy: 0.7376
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6090 - accuracy: 0.7364
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6085 - accuracy: 0.7377
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5970 - accuracy: 0.7209
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5733 - accuracy: 0.7374

In [44]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6018 - accuracy: 0.7261 - 479ms/epoch - 2ms/step
Loss: 0.6018338203430176, Accuracy: 0.726064145565033

In [45]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(